#!/bin/bash

# Hyprland borders theme module

source "$(dirname "${BASH_SOURCE[0]}")/base.sh"

hyprland_apply_theme() {
    local wallpaper="$1"
    local mode="$2"
    local state_file="$3"
    
    local module_name="Hyprland"
    
    # Check if Hyprland is running
    if ! pgrep -x Hyprland >/dev/null; then
        log_module "$module_name" "Not running, skipping"
        return 0
    fi
    
    log_module "$module_name" "Updating border colors for $mode theme"
    
    # Get colors from matugen generated lmtt-colors.css
    local colors_file="$HOME/.config/matugen/lmtt-colors.css"
    
    if [[ ! -f "$colors_file" ]]; then
        log_module "$module_name" "Colors file not found at $colors_file"
        return 1
    fi
    
    # Extract colors (remove # and @define-color prefix)
    local primary_color=$(grep "@define-color primary " "$colors_file" | sed 's/@define-color primary #//' | sed 's/;//' | head -1)
    local secondary_color=$(grep "@define-color secondary " "$colors_file" | sed 's/@define-color secondary #//' | sed 's/;//' | head -1)
    local outline_color=$(grep "@define-color outline " "$colors_file" | sed 's/@define-color outline #//' | sed 's/;//' | head -1)
    local shadow_color=$(grep "@define-color shadow " "$colors_file" | sed 's/@define-color shadow #//' | sed 's/;//' | head -1)
    
    if [[ -z "$primary_color" || -z "$outline_color" ]]; then
        log_module "$module_name" "Could not extract colors from $colors_file"
        return 1
    fi
    
    # Generate separate lmtt colors file for Hyprland
    local colors_config="$HOME/.config/hypr/lmtt-colors.conf"
    
    # Generate Hyprland color variables (not nested sections, just variable definitions)
    cat > "$colors_config" << EOF
# Generated by lmtt (Linux Matugen Theme Toggle)
# Material You color variables for Hyprland
# Mode: $mode
# These variables can be referenced in your Hyprland config

\$lmtt_primary = rgb($primary_color)
\$lmtt_secondary = rgb($secondary_color)
\$lmtt_outline = rgb($outline_color)
\$lmtt_active_border = rgb($primary_color) rgb($secondary_color) 45deg
\$lmtt_inactive_border = rgb($outline_color)
EOF

    # Add shadow color if available
    if [[ -n "$shadow_color" ]]; then
        cat >> "$colors_config" << EOF
\$lmtt_shadow = rgb($shadow_color)
EOF
    fi
    
    # Note: Hyprland will automatically pick up config changes
    log_module "$module_name" "Generated Hyprland colors: $colors_config"
    
    return 0
}

# Execute the function if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    hyprland_apply_theme "$@"
fi