#!/bin/bash

# WezTerm theme module

source "$(dirname "${BASH_SOURCE[0]}")/base.sh"

wezterm_apply_theme() {
    local wallpaper="$1"
    local mode="$2"
    local state_file="$3"
    local colors_json="$4"
    
    # Write colors to separate file that main config imports
    local colors_file="$HOME/.config/wezterm/wezterm-colors.lua"
    local module_name="WezTerm"
    
    # Check if WezTerm is installed
    if ! app_installed "wezterm"; then
        log_module "$module_name" "Not installed, skipping"
        return 0
    fi
    
    # Check if theme is already cached
    if theme_cached "$config_file" "$wallpaper" "$state_file"; then
        log_module "$module_name" "Theme cached, skipping regeneration"
        return 0
    fi
    
    log_module "$module_name" "Generating $mode theme"
    
    # Generate WezTerm config using Python with passed colors JSON
    python3 -c "
import json, sys

try:
    data = json.loads('$colors_json')
    colors = data.get('colors', {}).get('$mode', {})
    mode = '$mode'
    
    if mode == 'light':
        main_colors = {
            'foreground': colors.get('on_surface', '#1d1b20'),
            'background': colors.get('surface', '#fef7ff'),
            'cursor_bg': colors.get('primary', '#6750a4'),
            'cursor_fg': colors.get('on_primary', '#ffffff'),
            'cursor_border': colors.get('primary', '#6750a4'),
            'selection_fg': colors.get('on_primary_container', '#21005d'),
            'selection_bg': colors.get('primary_container', '#eaddff'),
        }
        ansi_colors = [
            colors.get('outline', '#79747e'),
            colors.get('error', '#ba1a1a'),
            '#2e7d32',  # green
            '#f57c00',  # yellow
            colors.get('primary', '#6750a4'),
            colors.get('on_surface_variant', '#625b71'),
            '#7d5260',  # cyan
            colors.get('on_surface', '#1d1b20')
        ]
        bright_colors = [
            colors.get('surface_container_high', '#e7e0ec'),
            colors.get('error', '#ba1a1a'),
            '#388e3c',  # bright green
            '#ff9800',  # bright yellow
            colors.get('primary', '#6750a4'),
            colors.get('on_surface_variant', '#625b71'),
            '#7d5260',  # bright cyan
            colors.get('on_surface', '#1d1b20')
        ]
    else:  # dark mode
        main_colors = {
            'foreground': colors.get('on_surface', '#e2e2e9'),
            'background': colors.get('surface', '#111318'),
            'cursor_bg': colors.get('primary', '#aac7ff'),
            'cursor_fg': colors.get('on_primary', '#09305f'),
            'cursor_border': colors.get('primary', '#aac7ff'),
            'selection_fg': colors.get('on_primary_container', '#d6e3ff'),
            'selection_bg': colors.get('primary_container', '#274777'),
        }
        ansi_colors = [
            colors.get('surface', '#111318'),
            colors.get('error', '#ffb4ab'),
            '#a5d6a7',  # green
            '#fff59d',  # yellow
            colors.get('primary', '#aac7ff'),
            colors.get('on_surface_variant', '#3e4759'),
            '#563e5c',  # cyan
            colors.get('on_surface', '#e2e2e9')
        ]
        bright_colors = [
            colors.get('surface_container', '#44474e'),
            colors.get('error', '#ffb4ab'),
            '#c8e6c9',  # bright green
            '#ffecb3',  # bright yellow
            colors.get('primary', '#aac7ff'),
            colors.get('on_surface_variant', '#3e4759'),
            '#563e5c',  # bright cyan
            colors.get('on_surface', '#e2e2e9')
        ]
    
    # Generate WezTerm colors module (just the colors table)
    colors_module = f'''-- WezTerm colors generated by theme switcher
-- This file is imported by the main wezterm.lua config
return {{
  foreground = '{main_colors['foreground']}',
  background = '{main_colors['background']}',
  cursor_bg = '{main_colors['cursor_bg']}',
  cursor_fg = '{main_colors['cursor_fg']}',
  cursor_border = '{main_colors['cursor_border']}',
  selection_fg = '{main_colors['selection_fg']}',
  selection_bg = '{main_colors['selection_bg']}',

  ansi = {{
''' + ',\\n'.join([f'    \\'{color}\\'' for color in ansi_colors]) + f''',
  }},

  brights = {{
''' + ',\\n'.join([f'    \\'{color}\\'' for color in bright_colors]) + f''',
  }},
}}'''
    
    with open('$colors_file', 'w') as f:
        f.write(colors_module)
    
    print('Generated WezTerm colors: $colors_file')
    
except Exception as e:
    print(f'Error generating WezTerm config: {e}')
    sys.exit(1)
"
    
    return $?
}