#!/bin/bash

# Hyprlock theme module

source "$(dirname "${BASH_SOURCE[0]}")/base.sh"

hyprlock_apply_theme() {
    local wallpaper="$1"
    local mode="$2"
    local state_file="$3"
    local colors_json="$4"
    
    local module_name="Hyprlock"
    local hyprlock_config="$HOME/.config/hypr/hyprlock.conf"
    
    # Check if hyprlock config exists
    if [[ ! -f "$hyprlock_config" ]]; then
        log_module "$module_name" "Config not found, skipping"
        return 0
    fi
    
    log_module "$module_name" "Generating lock screen colors for $mode theme"
    
    # Extract colors from JSON directly (no file dependency)
    local surface=$(echo "$colors_json" | jq -r ".colors.${mode}.surface")
    local on_surface=$(echo "$colors_json" | jq -r ".colors.${mode}.on_surface")
    local primary=$(echo "$colors_json" | jq -r ".colors.${mode}.primary")
    local primary_container=$(echo "$colors_json" | jq -r ".colors.${mode}.primary_container")
    local error=$(echo "$colors_json" | jq -r ".colors.${mode}.error")
    local secondary=$(echo "$colors_json" | jq -r ".colors.${mode}.secondary")
    
    # Convert hex to RGB for hyprlock format (no #)
    local rgb_surface="${surface#\#}"
    local rgb_on_surface="${on_surface#\#}"
    local rgb_primary="${primary#\#}"
    local rgb_primary_container="${primary_container#\#}"
    local rgb_error="${error#\#}"
    local rgb_secondary="${secondary#\#}"
    
    # Convert to decimal R, G, B values for rgba()
    local sr=$(printf "%d" 0x${rgb_surface:0:2})
    local sg=$(printf "%d" 0x${rgb_surface:2:2})
    local sb=$(printf "%d" 0x${rgb_surface:4:2})
    
    local pr=$(printf "%d" 0x${rgb_primary:0:2})
    local pg=$(printf "%d" 0x${rgb_primary:2:2})
    local pb=$(printf "%d" 0x${rgb_primary:4:2})
    
    # Generate separate lmtt colors file for hyprlock
    local colors_conf="$HOME/.config/hypr/lmtt-hyprlock-colors.conf"
    
    cat > "$colors_conf" << EOF
# Generated by lmtt (Linux Matugen Theme Toggle)
# Material You colors for hyprlock
# Mode: $mode

\$surface = rgb($rgb_surface)
\$on_surface = rgb($rgb_on_surface)
\$primary = rgb($rgb_primary)
\$primary_container = rgb($rgb_primary_container)
\$error = rgb($rgb_error)
\$secondary = rgb($rgb_secondary)

# RGBA versions for background
\$surface_rgba = rgba($sr, $sg, $sb, 1.0)
\$primary_rgba = rgba($pr, $pg, $pb, 1.0)
EOF
    
    log_module "$module_name" "Generated hyprlock colors: $colors_conf"
    
    return 0
}
