monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.usb-Bluetrum_USB_Audio.*" }
      { node.name = "~alsa_output.usb-SteelSeries_Arctis_Nova_7.*" }
      { node.name = "~alsa_output.pci-0000_c4_00.6.*" }
    ]
    actions = {
      update-props = {
        # Use software volume instead of the limited hardware mixer.
        # Gives a full perceptual cubic curve and allows >100% boost.
        api.alsa.soft-mixer = true
      }
    }
  }
]
