# Profile: Framework 16 internal panel only (no externals connected).
# Also serves as the lowest-priority fallback when no other profile matches.
#
#@ match = desc:BOE 0x0BC9
#@ edp = auto

monitor = eDP-2,2560x1600@165,0x0,1.25

workspace = 1, monitor:eDP-2, default:true
