description = "Dell S3422DWG ultrawide alone."
match = ["desc:Dell Inc. DELL S3422DWG HSRTS63"]

[[monitor]]
output = "desc:Dell Inc. DELL S3422DWG HSRTS63"
mode = "3440x1440@144"

[[workspace]]
workspace = "1"
monitor = "desc:Dell Inc. DELL S3422DWG HSRTS63"
default = true
