# Profile: Dell S3422DWG ultrawide alone.
#
#@ match = desc:Dell Inc. DELL S3422DWG HSRTS63
#@ edp = auto

monitor = desc:Dell Inc. DELL S3422DWG HSRTS63,3440x1440@144,0x0,auto

workspace = 1, monitor:desc:Dell Inc. DELL S3422DWG HSRTS63, default:true
