# Profile: Dell S3422DWG ultrawide (primary) + S2721QS rotated portrait (secondary).
#
#@ match = desc:Dell Inc. DELL S3422DWG HSRTS63
#@ match = desc:Dell Inc. DELL S2721QS 6VSGM43
#@ edp = auto

monitor = desc:Dell Inc. DELL S3422DWG HSRTS63,3440x1440@144,0x0,auto
monitor = desc:Dell Inc. DELL S2721QS 6VSGM43,highres,3440x0,1.5,transform,3

workspace = 1, monitor:desc:Dell Inc. DELL S3422DWG HSRTS63, default:true
