# Fuzzel configuration
include=~/.config/fuzzel/lmtt-colors.ini

[main]
font=monospace:size=12
dpi-aware=auto
width=50
lines=15
horizontal-pad=20
vertical-pad=10
inner-pad=5

[border]
width=2
radius=8
