-- WezTerm colors generated by theme switcher
-- This file is imported by the main wezterm.lua config
return {
  foreground = '#e3e1ec',
  background = '#12131a',
  cursor_bg = '#9fd491',
  cursor_fg = '#083906',
  cursor_border = '#9fd491',
  selection_fg = '#baf1aa',
  selection_bg = '#22511c',

  ansi = {
    '#12131a',
    '#ffb4ab',
    '#a5d6a7',
    '#fff59d',
    '#9fd491',
    '#c5c5d6',
    '#563e5c',
    '#e3e1ec',
  },

  brights = {
    '#1e1f27',
    '#ffb4ab',
    '#c8e6c9',
    '#ffecb3',
    '#9fd491',
    '#c5c5d6',
    '#563e5c',
    '#e3e1ec',
  },
}