# Shader cache (AMD)
MESA_SHADER_CACHE_MAX_SIZE=12G

# AMD Anti-Lag (RDNA+)
ENABLE_LAYER_MESA_ANTI_LAG=1

# RADV persistent cache (faster load times)
RADV_ENABLE_PERSISTENT_CACHE=1

# RADV transfer queue (GFX9+)
RADV_PERFTEST=transfer_queue

# Reduce latency from dynamic linking
LD_BIND_NOW=1
