# E2E Testing Configuration

# Test execution settings
test:
  timeout_seconds: 1800  # 30 minutes for full test suite
  chezmoi_init_timeout: 300  # 5 minutes for chezmoi init
  chezmoi_apply_timeout: 900  # 15 minutes for chezmoi apply
  ssh_connect_timeout: 60
  retry_count: 3
  parallel_vms: true

# Chezmoi repository settings
chezmoi:
  repo_url: "https://github.com/user/dotfiles.git"  # Update with actual repo
  branch: "main"
  test_user: "testuser"
  test_user_password: "testpass123"

# VM resource allocation
vm:
  memory_mb: 4096
  cpu_cores: 2
  disk_size_gb: 20
  network: "user"  # NAT networking

# Distribution configurations
distributions:
  arch:
    enabled: true
    base_image: "arch-base.qcow2"
    package_manager: "pacman"
    chezmoi_install_cmd: "sudo pacman -S --noconfirm chezmoi"

  fedora:
    enabled: true
    base_image: "fedora-base.qcow2"
    package_manager: "dnf"
    chezmoi_install_cmd: "sudo dnf install -y chezmoi"

# Error detection patterns
error_patterns:
  - "Error:"
  - "FAILED"
  - "fatal:"
  - "command not found"
  - "Permission denied"
  - "No space left on device"
  - "chezmoi: error:"

# Success indicators
success_patterns:
  - "chezmoi: no differences"
  - "Apply complete"
  - "Installation complete"

# Artifact collection
artifacts:
  collect_logs: true
  collect_screenshots: true
  collect_config_files: true
  output_dir: "test_results"