# VM Infrastructure Configuration

# Base image build settings
base_images:
  arch:
    iso_url: "https://mirrors.kernel.org/archlinux/iso/latest/archlinux-x86_64.iso"
    iso_checksum_url: "https://mirrors.kernel.org/archlinux/iso/latest/sha256sums.txt"
    output_name: "arch-base.qcow2"

  fedora:
    iso_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/39/Server/x86_64/iso/Fedora-Server-netinst-x86_64-39-1.5.iso"
    iso_checksum: "sha256:12345..."  # Update with actual checksum
    output_name: "fedora-base.qcow2"

# QEMU runtime settings
qemu:
  accelerator: "kvm"  # Use TCG if KVM unavailable
  machine_type: "q35"
  graphics: "vnc=:1"  # VNC display for screenshots
  monitor: "unix:/tmp/qemu-monitor.sock,server,nowait"

# Cloud-init settings
cloud_init:
  datasource: "NoCloud"
  user_data_template: "user-data.yaml.j2"
  meta_data_template: "meta-data.yaml.j2"

# Network configuration
network:
  type: "user"
  hostfwd_ssh: "tcp::2222-:22"  # Forward host 2222 to guest 22
  dns: "8.8.8.8"

# Storage settings
storage:
  format: "qcow2"
  cache: "writeback"
  backing_images_dir: "images/base/"
  test_images_dir: "images/test/"