# Fish shell colors generated by matugen
# This file is sourced automatically from conf.d/

# Basic colors
set -g fish_color_normal '{{colors.on_surface.hex}}'
set -g fish_color_command '{{colors.primary.hex}}'
set -g fish_color_param '{{colors.on_surface.hex}}'
set -g fish_color_redirection '{{colors.secondary.hex}}'
set -g fish_color_comment '{{colors.outline.hex}}'
set -g fish_color_error '{{colors.error.hex}}'
set -g fish_color_escape '{{colors.tertiary.hex}}'
set -g fish_color_operator '{{colors.primary.hex}}'
set -g fish_color_quote '{{colors.secondary.hex}}'
set -g fish_color_autosuggestion '{{colors.outline.hex}}'

# Selection colors
set -g fish_color_selection --background='{{colors.primary_container.hex}}'
set -g fish_color_search_match --background='{{colors.tertiary_container.hex}}'

# Completion pager colors - using brighter/more visible colors
set -g fish_pager_color_completion '{{colors.on_surface.hex}}'
set -g fish_pager_color_description '{{colors.on_surface_variant.hex}}'
set -g fish_pager_color_prefix '{{colors.primary.hex}}'
set -g fish_pager_color_progress '{{colors.outline.hex}}'
set -g fish_pager_color_selected_background --background='{{colors.surface_container_high.hex}}'
