--enable-features=UseOzonePlatform,WaylandWindowDecorations,CanvasOopRasterization,EnableDrDc
--ozone-platform-hint=auto
--enable-wayland-ime
--use-gl=egl
--enable-gpu-rasterization
--enable-zero-copy